---
title: "Roger Peyrefitte's Diplomatic Journeys"
author: "Josh Sulkin"
date: "5/17/2023"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE}
library(spDataLarge)
library(leaflet)
library(sf)
library(tmap)
library(terra)
library(dplyr)
library(spData)
library(tidyverse)
library(tidygeocoder)
library(vtable)
library(ggmap)
library(tmaptools)
library(mapview)
library(lattice)
library(leafpop)
library(mapview)
library(shiny)
library(bslib)
```

```{r import, message=FALSE, include=FALSE}
setwd("~/GIS Classes/GISC_284_FINAL_PROJECT")
Peyrefitte <- st_read("Updated_Peyrefitte.shp")
GeoPeyrefitte <- st_as_sf(Peyrefitte, coords = c("x", "y"), crs = 27572)
```

# The Digitized Diplomat

```{r include=FALSE}
tmap_mode("view")
Peyrefitte_Map <- tm_shape(GeoPeyrefitte) + 
  tm_dots("red", 
          size=0.15, 
          id="Location", 
          popup.vars=c(' ' = 'Descriptio'))
```

```{r}
Peyrefitte_Map
```
